@startuml 02-caso-uso-registrar-turno-medico-01


left to right direction

actor "Paciente" as Paciente
actor "Secretaria" as Secretaria

rectangle "Sistema de Turnos Medico" {
    usecase "Registrar Turno Médico" as UC1
    usecase "Verificar Registro\nde Paciente" as UC2
    usecase "Verificar Registro\nde Médico" as UC3
    usecase "Confirmar Reserva" as UC4
    usecase "Registrar en Historial" as UC5
}

Paciente --> UC1
Secretaria --> UC1

UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>
UC1 ..> UC4 : <<include>>
UC1 ..> UC5 : <<include>>

@enduml

