@startuml 02-caso-uso-administrar-disponibilidad-05

left to right direction

actor "Médico" as Medico
actor "Secretaria" as Secretaria

rectangle "Sistema de Turnos Medico" {
    usecase "Administrar Disponibilidad\ndel Profesional" as UC1
    usecase "Definir Horarios\nde Atención" as UC2
    usecase "Registrar Bloqueos\no Licencias" as UC3
    usecase "Validar Conflictos\ncon Turnos" as UC4
}

Medico --> UC1
Secretaria --> UC1

UC1 ..> UC2 : <<include>>
UC1 ..> UC4 : <<include>>
UC1 ..> UC3 : <<extend>>

@enduml